/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "SAYAKU",
  "tagline": "喜歡鐵道單車咖啡的前端碼農",
  "url": "https://sayaku.github.io",
  "baseUrl": "/",
  "onBrokenLinks": "warn",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "img/favicon.ico",
  "trailingSlash": false,
  "organizationName": "sayaku",
  "projectName": "sayaku.github.io",
  "i18n": {
    "defaultLocale": "zh-TW",
    "locales": [
      "zh-TW"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "plugins": [
    "/Users/sayaku/Documents/blog/sayaku.github.io/node_modules/docusaurus-plugin-image-zoom/src/index.js",
    [
      "docusaurus2-dotenv",
      {
        "systemvars": true
      }
    ]
  ],
  "themes": [
    "@saucelabs/theme-github-codeblock"
  ],
  "themeConfig": {
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 5
    },
    "metadata": [
      {
        "name": "robots",
        "content": "max-image-preview:large"
      },
      {
        "name": "og:type",
        "content": "article"
      },
      {
        "name": "fb:app_id",
        "content": "173025689387886"
      }
    ],
    "docs": {
      "sidebar": {
        "hideable": true,
        "autoCollapseCategories": false
      },
      "versionPersistence": "localStorage"
    },
    "zoom": {
      "selector": ".markdown :not(em,a) > img",
      "config": {
        "background": {
          "light": "rgb(255, 255, 255)",
          "dark": "rgb(50, 50, 50)"
        }
      }
    },
    "prism": {
      "additionalLanguages": [
        "powershell",
        "csharp",
        "cshtml",
        "java",
        "php",
        "aspnet",
        "toml"
      ],
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#9CDCFE",
          "backgroundColor": "#1E1E1E"
        },
        "styles": [
          {
            "types": [
              "prolog"
            ],
            "style": {
              "color": "rgb(0, 0, 128)"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(106, 153, 85)"
            }
          },
          {
            "types": [
              "builtin",
              "changed",
              "keyword",
              "interpolation-punctuation"
            ],
            "style": {
              "color": "rgb(86, 156, 214)"
            }
          },
          {
            "types": [
              "number",
              "inserted"
            ],
            "style": {
              "color": "rgb(181, 206, 168)"
            }
          },
          {
            "types": [
              "constant"
            ],
            "style": {
              "color": "rgb(100, 102, 149)"
            }
          },
          {
            "types": [
              "attr-name",
              "variable"
            ],
            "style": {
              "color": "rgb(156, 220, 254)"
            }
          },
          {
            "types": [
              "deleted",
              "string",
              "attr-value",
              "template-punctuation"
            ],
            "style": {
              "color": "rgb(206, 145, 120)"
            }
          },
          {
            "types": [
              "selector"
            ],
            "style": {
              "color": "rgb(215, 186, 125)"
            }
          },
          {
            "types": [
              "tag"
            ],
            "style": {
              "color": "rgb(78, 201, 176)"
            }
          },
          {
            "types": [
              "tag"
            ],
            "languages": [
              "markup"
            ],
            "style": {
              "color": "rgb(86, 156, 214)"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "rgb(212, 212, 212)"
            }
          },
          {
            "types": [
              "punctuation"
            ],
            "languages": [
              "markup"
            ],
            "style": {
              "color": "#808080"
            }
          },
          {
            "types": [
              "function"
            ],
            "style": {
              "color": "rgb(220, 220, 170)"
            }
          },
          {
            "types": [
              "class-name"
            ],
            "style": {
              "color": "rgb(78, 201, 176)"
            }
          },
          {
            "types": [
              "char"
            ],
            "style": {
              "color": "rgb(209, 105, 105)"
            }
          }
        ]
      },
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "navbar": {
      "title": "SAYAKU",
      "logo": {
        "alt": "Site Logo",
        "src": "img/logo.png"
      },
      "items": [
        {
          "type": "doc",
          "docId": "intro/intro",
          "position": "left",
          "label": "文件庫"
        },
        {
          "to": "/blog",
          "label": "部落格",
          "position": "left"
        },
        {
          "to": "pathname:///slides",
          "label": "投影片",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "copyright": "Copyright © 2022 Sayaku lin(林克融). Built with Docusaurus.",
      "links": []
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    }
  },
  "presets": [
    [
      "@docusaurus/preset-classic",
      {
        "googleAnalytics": {
          "trackingID": "UA-20523508-2",
          "anonymizeIP": true
        },
        "docs": {
          "sidebarPath": "/Users/sayaku/Documents/blog/sayaku.github.io/sidebars.js",
          "editUrl": "https://github.com/sayaku/sayaku.github.io/edit/main",
          "remarkPlugins": [
            null,
            null
          ],
          "rehypePlugins": [
            [
              null,
              {
                "strict": false
              }
            ]
          ],
          "showLastUpdateAuthor": true,
          "showLastUpdateTime": true,
          "breadcrumbs": true
        },
        "blog": {
          "blogSidebarCount": 0,
          "showReadingTime": true,
          "editUrl": "https://github.com/sayaku/sayaku.github.io/edit/main",
          "remarkPlugins": [
            null,
            null
          ],
          "rehypePlugins": [
            [
              null,
              {
                "strict": false
              }
            ]
          ]
        },
        "theme": {
          "customCss": "/Users/sayaku/Documents/blog/sayaku.github.io/src/css/custom.css"
        }
      }
    ]
  ],
  "stylesheets": [
    {
      "href": "https://cdn.jsdelivr.net/npm/katex@0.13.11/dist/katex.min.css",
      "type": "text/css",
      "integrity": "sha384-Um5gpz1odJg5Z4HAmzPtgZKdTBHZdw8S29IecapCSB31ligYPhHQZMIlWLYQGVoc",
      "crossorigin": "anonymous"
    },
    {
      "rel": "preconnect",
      "href": "https://fonts.googleapis.com"
    },
    {
      "rel": "preconnect",
      "href": "https://fonts.gstatic.com",
      "crossorigin": "anonymous"
    },
    {
      "rel": "stylesheet",
      "href": "https://fonts.googleapis.com/css2?family=Noto+Sans+TC:wght@400;700;900&display=swap"
    }
  ],
  "scripts": [
    {
      "src": "https://cdnjs.cloudflare.com/ajax/libs/pangu/4.0.7/pangu.min.js",
      "async": true
    },
    {
      "src": "/assets/enablePangu.js",
      "async": true
    }
  ],
  "baseUrlIssueBanner": true,
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
